from aiogram.fsm.state import StatesGroup, State


class AnnouncementCreationStates(StatesGroup):
    ENTER_VIEWING_TIME = State()
    ENTER_ADDRESS = State()
    ENTER_DISTRICT = State()
    ENTER_MICRODISTRICT = State()
    SHARE_LOCATION = State()
    SELECT_TECHNOLOGY = State()
    SELECT_OWNERSHIP_TYPE = State()
    SELECT_PROPERTY_TYPE = State()
    SELECT_BEDROOMS = State()
    SELECT_BATHROOMS = State()
    ENTER_KITCHEN_AREA = State()
    SELECT_HEATING = State()
    SELECT_HAS_BALCONY_OR_LOGGIA = State()
    SELECT_HAS_MORTGAGE = State()
    SELECT_HAS_HEATING = State()
    SELECT_HAS_BATHROOMS = State()
    SELECT_COMMISSION_TO_AGENT = State()
    SELECT_CONDITION = State()
    SELECT_FINISHING = State()
    SELECT_ROOMS = State()
    ENTER_AREA = State()
    SELECT_CALL_METHOD = State()
    ENTER_DESCRIPTION = State()
    ENTER_PRICE = State()
    UPLOAD_SCHEME = State()
    UPLOAD_GALLERY = State()
